wandb_version: 1

model_name:
  desc: null
  value: cl-tohoku/bert-base-japanese-v3
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 5.0e-05
experiment_type:
  desc: null
  value: normal
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714961600.0
    t:
      1:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 12
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.1
      8:
      - 1
      - 5
      - 12
      13: linux-x86_64
